services:
  web:
    image: alfg/nginx-rtmp
    container_name: mumble-video-rtmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
    ports:
      - "1935:1935/tcp"
      - "1935:1935/udp"
